IATA_MAP: dict[str, str] = {
    # India
    "delhi": "DEL", "new delhi": "DEL",
    "mumbai": "BOM", "bombay": "BOM",
    "bengaluru": "BLR", "bangalore": "BLR",
    "ahmedabad": "AMD",
    "goa": "GOI",
    "kolkata": "CCU", "calcutta": "CCU",
    "chennai": "MAA", "madras": "MAA",
    "hyderabad": "HYD",
    "pune": "PNQ",
    "jaipur": "JAI",
    "kochi": "COK", "cochin": "COK",
    "lucknow": "LKO",
    "vadodara": "BDQ", "baroda": "BDQ",
    "surat": "STV",
    "indore": "IDR",
    "bhopal": "BHO",
    "nagpur": "NAG",
    "patna": "PAT",
    "ranchi": "IXR",
    "bhubaneswar": "BBI",
    "guwahati": "GAU",
    "amritsar": "ATQ",
    "chandigarh": "IXC",
    "coimbatore": "CJB",
    "mangalore": "IXE", "mangaluru": "IXE",
    "trichy": "TRZ", "tiruchirappalli": "TRZ",
    "varanasi": "VNS",
    "leh": "IXL",
    "srinagar": "SXR",
    "jammu": "IXJ",
    "jodhpur": "JDH",
    "udaipur": "UDR",
    "raipur": "RPR",
    "visakhapatnam": "VTZ", "vizag": "VTZ",
    "vijayawada": "VGA",
    "thiruvananthapuram": "TRV", "trivandrum": "TRV",
    "kozhikode": "CCJ", "calicut": "CCJ",
    "dibrugarh": "DIB",
    "imphal": "IMF",
    "bagdogra": "IXB",
    "port blair": "IXZ",
    "hubli": "HBX",
    "tirupati": "TIR",
    "dehradun": "DED",
    "gwalior": "GWL",
    # International
    "dubai": "DXB",
    "abu dhabi": "AUH",
    "sharjah": "SHJ",
    "singapore": "SIN",
    "bangkok": "BKK",
    "london": "LHR",
    "new york": "JFK",
    "paris": "CDG",
    "bali": "DPS", "denpasar": "DPS",
    "kuala lumpur": "KUL",
    "colombo": "CMB",
    "kathmandu": "KTM",
    "doha": "DOH",
    "muscat": "MCT",
    "toronto": "YYZ",
    "sydney": "SYD",
    "melbourne": "MEL",
    "tokyo": "NRT",
    "hong kong": "HKG",
}


def city_to_iata(city_name: str) -> str | None:
    if not city_name:
        return None
    return IATA_MAP.get(city_name.strip().lower())
